name: Deploy by CDK
description: CDKを使ってデプロイする

inputs:
  # 以下は必須
  aws-role:
    description: AWS OIDC Role for environment
    required: true
  # 以下は任意
  environment:
    required: true
    description: 環境名
    default: "production"
  target-stack:
    required: true
    description: デプロイ対象のスタック名
    default: "--all"
  region:
    description: aws region
    required: false
    default: "ap-northeast-1"
  workdir:
    required: false
    description: デプロイ対象のディレクトリ
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    # - name: Cache npm directory
    #   uses: actions/cache@v3
    #   with:
    #     path: ${{ inputs.workdir }}/.npm
    #     key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
    #     restore-keys: ${{ runner.os }}-npm-

    - name: Setup dependencies
      working-directory: ${{ inputs.workdir }}
      run: |
        node -v; npm -v
        npm ci
      shell: sh

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role }}
        aws-region: ${{ inputs.region }}

    - name: CDK Deploy
      working-directory: ${{ inputs.workdir }}
      run: npx cdk -c "env=$ENV" deploy "$TARGET_STACK" --require-approval never
      shell: sh
      env:
        ENV: ${{ inputs.environment }}
        TARGET_STACK: ${{ inputs.target-stack }}
        AWS_DEFAULT_REGION: ${{ inputs.region }}
